/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drones;
import javax.swing.*;
import java.awt.*;
import java.awt.image.*;
import java.io.*;
import javax.imageio.*;
import java.util.ArrayList;
import java.util.concurrent.Semaphore;
import java.util.concurrent.locks.Condition;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

/**
 *
 * @author Jorge
 */
public class Drones extends javax.swing.JFrame {

    public Drones() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        try{
            ima = ImageIO.read(new File ("C:\\Users\\Jorge\\Pictures\\mapaCU.png"));
        }catch(IOException e){e.printStackTrace();}
        
        initComponents();
        mutexVC = new ReentrantLock();
        condicion = mutexVC.newCondition();
        bandera = true;
        barrera = new Barrier(1);
        mutex = new ReentrantLock();
        semaforo = new Semaphore(1);
        x = new MiX(0);
        y= new MiY(0);
        n = new NumDrones();
        datosX = new double[1000];
        datosY = new double[1000];
        drones = new ArrayList<Dron>();
        panel = new DibujaDrones(x,y,n,ima, 4,metodo);
        panelG = new gPerformed();
        panel.setBounds(25,50,700,400);
        panel.setBackground(new Color(135,206,235));
        add(panel);
        panelG.setBounds(750, 0, 600, 500);
        add(panelG);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Drones");

        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sincronización");

        jMenuItem5.setText("Sin Sincronización");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem3.setText("Mutex");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Semaforos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem6.setText("Monitores");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Variable de Condicion");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Barreras");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.out.println(x1);
        if(cont<3){
            crearDron();
            determinaParidad();
        }else{
            int j=0;
            while(j<2 && cont<11){
                if(cont<5) y1 = 200;
                
                if(cont >= 5 && cont<7) y1 = 266;
                
                if(cont >= 7 && cont<9) y1=300;
                
                if(cont >= 9 && cont<11) y1=320;
                
                crearDron();
                determinaParidad();
                j++;
            }
        }
        reubicarDrones();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    public void reubicarDrones(){
        for(Dron d: drones){
            d.setTotalDrones(cont-1);
            int px1=0, px2=350, py=0;
            
            if(drones.size()==1){
                if(d.getNumero()==1){
                    d.setX(new MiX(px1));d.setY(new MiY(py));
                    d.setTop(0); d.setBottom(400); d.setRight(700); d.setLef(0);
                }
            }
            
            if(drones.size()==2){
                if(d.getNumero()==1){
                    d.setX(new MiX(px1));d.setY(new MiY(py));d.setRight(350);
                }
                if(d.getNumero()==2){
                    d.setX(new MiX(px2));d.setY(new MiY(py));
                    d.setTop(0); d.setBottom(400); d.setRight(700); d.setLef(350);
                }
            }
            
            if(drones.size()==4){
                if(d.getNumero()==1){d.setX(new MiX(px1));d.setY(new MiY(py));d.setBottom(200);}
                if(d.getNumero()==2){d.setX(new MiX(px2));d.setY(new MiY(py));d.setBottom(200);}
                py=210;
                if(d.getNumero()==3){
                    d.setX(new MiX(px1));d.setY(new MiY(py));
                    d.setTop(200); d.setBottom(400); d.setRight(350); d.setLef(0);
                }
                if(d.getNumero()==4){
                    d.setX(new MiX(px2));d.setY(new MiY(py));
                    d.setTop(200); d.setBottom(400); d.setRight(700); d.setLef(350);
                }
            }
            
            if(drones.size()==6){
                if(d.getNumero()==1){d.setX(new MiX(px1));d.setY(new MiY(py));d.setBottom(133);}
                if(d.getNumero()==2){d.setX(new MiX(px2));d.setY(new MiY(py));d.setBottom(133);}
                py=133;
                if(d.getNumero()==3){d.setX(new MiX(px1));d.setY(new MiY(py));d.setTop(133); d.setBottom(266);}
                if(d.getNumero()==4){d.setX(new MiX(px2));d.setY(new MiY(py));d.setTop(133); d.setBottom(266);}
                py=266;
                if(d.getNumero()==5){
                    d.setX(new MiX(px1));d.setY(new MiY(py));
                    d.setTop(266); d.setBottom(400); d.setRight(350); d.setLef(0);
                }
                if(d.getNumero()==6){
                    d.setX(new MiX(px2));d.setY(new MiY(py));
                    d.setTop(266); d.setBottom(400); d.setRight(700); d.setLef(350);
                }
            }
            
            if(drones.size()==8){
                if(d.getNumero()==1){d.setX(new MiX(px1));d.setY(new MiY(py));d.setBottom(100);}
                if(d.getNumero()==2){d.setX(new MiX(px2));d.setY(new MiY(py));d.setBottom(100);}
                py=100;
                if(d.getNumero()==3){d.setX(new MiX(px1));d.setY(new MiY(py));d.setTop(100);d.setBottom(200);}
                if(d.getNumero()==4){d.setX(new MiX(px2));d.setY(new MiY(py));d.setTop(100);d.setBottom(200);}
                py=200;
                if(d.getNumero()==5){d.setX(new MiX(px1));d.setY(new MiY(py));d.setTop(200);d.setBottom(300);}
                if(d.getNumero()==6){d.setX(new MiX(px2));d.setY(new MiY(py));d.setTop(200);d.setBottom(300);}
                py=300;
                if(d.getNumero()==7){
                    d.setX(new MiX(px1));d.setY(new MiY(py));
                    d.setTop(300); d.setBottom(400); d.setRight(350); d.setLef(0);
                }
                if(d.getNumero()==8){
                    d.setX(new MiX(px2));d.setY(new MiY(py));
                    d.setTop(300); d.setBottom(400); d.setRight(700); d.setLef(350);
                }
            }
            
            if(drones.size()==10){
                if(d.getNumero()==1){d.setX(new MiX(px1));d.setY(new MiY(py));d.setBottom(80);}
                if(d.getNumero()==2){d.setX(new MiX(px2));d.setY(new MiY(py));d.setBottom(80);}
                py=80;
                if(d.getNumero()==3){d.setX(new MiX(px1));d.setY(new MiY(py));d.setTop(80);d.setBottom(160);}
                if(d.getNumero()==4){d.setX(new MiX(px2));d.setY(new MiY(py));d.setTop(80);d.setBottom(160);}
                py=160;
                if(d.getNumero()==5){d.setX(new MiX(px1));d.setY(new MiY(py));d.setTop(160);d.setBottom(240);}
                if(d.getNumero()==6){d.setX(new MiX(px2));d.setY(new MiY(py));d.setTop(160);d.setBottom(240);}
                py=240;
                if(d.getNumero()==7){d.setX(new MiX(px1));d.setY(new MiY(py));d.setTop(240);d.setBottom(320);}
                if(d.getNumero()==8){d.setX(new MiX(px2));d.setY(new MiY(py));d.setTop(240);d.setBottom(320);}
                py=320;
                if(d.getNumero()==9){
                    d.setX(new MiX(px1));d.setY(new MiY(py));
                    d.setTop(320); d.setBottom(400); d.setRight(350); d.setLef(0);
                }
                if(d.getNumero()==10){
                    d.setX(new MiX(px2));d.setY(new MiY(py));
                    d.setTop(320); d.setBottom(400); d.setRight(700); d.setLef(350);
                }
            }
            if (!d.isAlive())
                try{
                   d.start(); 
                }catch(Exception e){System.out.println(e);}
        }
    }
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        panel.setMetodo(1);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (cont>3) {
            drones.get(drones.size()-1).stop();
            drones.remove(drones.size()-1);
            drones.get(drones.size()-1).stop();
            drones.remove(drones.size()-1);
            cont-=2;
            reubicarDrones();
        }else{
            if (cont>1 && cont<=3) {
                drones.get(drones.size()-1).stop();
                drones.remove(drones.size()-1);
                cont-=1;
                reubicarDrones();
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        panel.setMetodo(2);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        panel.setMetodo(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        panel.setMetodo(3);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        panel.setMetodo(5);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        panel.setMetodo(4);
    }//GEN-LAST:event_jMenuItem7ActionPerformed
    
    public void crearDron(){
        x = new MiX(x1);
        y = new MiY(y1);
        drones.add(new Dron(panel, panelG, x, y, cont, mutex, semaforo, barrera, mutexVC, condicion, bandera));
        cont++;
        panel.setDrones(drones);
    }
    
    public void determinaParidad(){
        if (cont%2==0) {
            x1=360;
        }else{
            x1=0;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Drones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables
    private DibujaDrones panel;
    private gPerformed panelG;
    private double[] datosX;
    private double[] datosY;
    
    private MiX x;
    private MiY y;
    private NumDrones n;
    private Dron b1;
    private BufferedImage ima; //Nueva
    private ArrayList<Dron> drones;
    int x1=0;
    int y1=0;
    int cont=1;
    int metodo = 0;
    private Lock mutex;
    private Semaphore semaforo;
    private Barrier barrera;
    private Lock mutexVC;
    private Condition condicion;
    private boolean bandera;
}
